"""Compact MCP replies before they are placed in a model conversation.

The registry and executor retain complete parameter and scheduler diagnostics
for validation and audit. Those objects are not suitable as repeated model
tool outputs: a scheduler snapshot can contain an entire cluster queue and a
generic candidate can contain every parameter of an unrelated job type. This
module changes presentation only; execution still uses the original objects.
"""
from __future__ import annotations

from typing import Any


def compact_candidate_action(candidate: dict[str, Any]) -> dict[str, Any]:
    """Keep every candidate while replacing verbose schemas with an index.

    This is deliberately an *action index*, not a second validator.  The
    complete candidate continues to be regenerated by the executor before a
    decision is validated. In particular, a model can still select every
    action that was previously visible; it only asks
    ``get_candidate_action_details`` when it needs a non-default parameter's
    full schema.
    """
    template = candidate.get("parameter_template") or {}
    required = sorted(
        name for name, spec in template.items()
        if isinstance(spec, dict) and spec.get("required")
    )
    parameter_interface: dict[str, Any] = {
        "required_parameters": required,
        "details_available_via": "get_candidate_action_details",
    }
    # Import candidates are the one case whose deterministic defaults are
    # fixed acquisition facts.  Keep those visible without privileging any
    # later scientific parameter choice.
    defaults = candidate.get("default_parameters") or {}
    if candidate.get("workflow_stage") == "import" and defaults:
        parameter_interface["default_parameters"] = defaults

    # The repeated per-turn index must remain small enough that the model can
    # receive an execution response *and* a terminal result in one SDK turn.
    # Action id/type and job type preserve the complete selectable set. The
    # full candidate can be looked up individually without changing what the
    # executor validates or connects.
    result = {
        key: candidate[key]
        for key in ("action_id", "action_type", "job_type", "available")
        if candidate.get(key) is not None
    }
    if candidate.get("execution_mode") not in {None, "create_job"}:
        result["execution_mode"] = candidate["execution_mode"]
    if candidate.get("blocked_by"):
        result["blocked_by"] = candidate["blocked_by"]
    if candidate.get("missing_required_inputs"):
        result["missing_required_inputs"] = candidate["missing_required_inputs"]
    required_inputs = candidate.get("required_inputs") or {}
    if required_inputs:
        # Source identities are retained internally for connection planning;
        # the model only needs to know which slots are already satisfiable.
        result["available_input_slots"] = sorted(required_inputs)
    result["parameter_interface"] = parameter_interface
    return result


def compact_candidate_actions(candidates: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [compact_candidate_action(candidate) for candidate in candidates]


def compact_candidate_context_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Return a copy whose model-visible candidate lists are bounded."""
    result = dict(payload)
    for key in ("candidate_actions", "blocked_actions", "next_candidate_actions"):
        if isinstance(result.get(key), list):
            result[key] = compact_candidate_actions(result[key])
    return result


def compact_execution_response(response: dict[str, Any]) -> dict[str, Any]:
    """Expose created Job identities, not duplicated executor internals."""
    execution = response.get("execution_result") or {}
    return {
        "success": response.get("success"),
        "dry_run": response.get("dry_run"),
        "execution_mode": response.get("execution_mode"),
        "candidate_context": response.get("candidate_context"),
        "internal_decision": response.get("internal_decision"),
        "execution_result": {
            key: execution.get(key)
            for key in ("success", "dry_run", "execution_mode", "decision_type", "message")
            if key in execution
        } | {
            "execution_results": [
                compact_execution_result(result)
                for result in execution.get("execution_results", [])
            ],
            "issues": execution.get("issues") or [],
            "warnings": execution.get("warnings") or [],
        },
        "issues": response.get("issues") or [],
        "warnings": response.get("warnings") or [],
    }


def compact_execution_result(result: dict[str, Any]) -> dict[str, Any]:
    """Retain all fields required for runner Job waiting and error diagnosis."""
    compacted = {
        key: result.get(key)
        for key in (
            "success", "dry_run", "status", "project_uid", "workspace_uid",
            "job_uid", "job_type", "queued", "logical_workflow_step",
            "approval_required", "approval_reasons", "human_action_required",
            "error", "error_type", "issues",
        ) if key in result
    }
    logical = result.get("logical_job")
    if isinstance(logical, dict):
        compacted["logical_job"] = {
            key: logical.get(key)
            for key in (
                "logical_job_id", "logical_job_uid", "physical_job_ids",
                "winner_job_uid", "race_statuses", "cancellations",
            ) if key in logical
        }
    diagnostics = result.get("diagnostics")
    if isinstance(diagnostics, dict):
        compacted["diagnostics"] = {
            key: diagnostics.get(key)
            for key in ("execution_phase", "http_response") if key in diagnostics
        }
    return compacted
